# Generated by Django 5.2.15 on 2026-06-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_professional_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_privacy_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
