# Generated by Django 5.2.15 on 2026-06-26 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_accepted_privacy_at_user_accepted_terms_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionalprofile',
            name='catalog_status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em analise'), ('published', 'Publicado'), ('paused', 'Pausado'), ('rejected', 'Recusado')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_professional_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='verified_by_apelmat',
            field=models.BooleanField(default=False),
        ),
    ]
