# Generated by Django 5.2.15 on 2026-06-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_professionalprofile_catalog_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractorprofile',
            options={'verbose_name': '03. Empresa', 'verbose_name_plural': '03. Empresas'},
        ),
        migrations.AlterModelOptions(
            name='professionalprofile',
            options={'verbose_name': '02. Curriculo profissional', 'verbose_name_plural': '02. Curriculos profissionais'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '01. Usuario', 'verbose_name_plural': '01. Usuarios'},
        ),
    ]
