# Generated by Codex on 2026-07-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_contractorprofile_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("professional", "Profissional"),
                    ("contractor", "Contratante"),
                    ("both", "Ambos"),
                ],
                default="professional",
                max_length=20,
            ),
        ),
    ]
