# Generated by Django 5.2.15 on 2026-06-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_seed_apelmat_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='kind',
            field=models.CharField(choices=[('job', 'Emprego'), ('service', 'Servico')], default='service', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('new_resume', 'Novo curriculo'), ('new_opportunity', 'Nova oportunidade'), ('application', 'Candidatura'), ('application_status', 'Status da candidatura')], max_length=30),
        ),
    ]
