# Generated by Django 5.2.15 on 2026-06-22 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_seed_general_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='listing_type',
            field=models.CharField(choices=[('work_offer', 'Profissional oferecendo trabalho'), ('hiring', 'Contratante buscando profissional')], default='hiring', max_length=20),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['listing_type', 'status'], name='marketplace_listing_eb8abe_idx'),
        ),
    ]
