# Generated by Django 5.2.15 on 2026-06-26 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_opportunity_listing_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('new_resume', 'Novo curriculo'), ('new_opportunity', 'Nova oportunidade'), ('application', 'Candidatura'), ('application_status', 'Status da candidatura'), ('profile_review', 'Analise de curriculo'), ('contact_request', 'Solicitacao de contato'), ('contact_released', 'Contato liberado'), ('contact_rejected', 'Contato recusado')], max_length=30),
        ),
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Em analise'), ('approved', 'Contato liberado'), ('rejected', 'Recusado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('release_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests_made', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests_decided', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='contact_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='marketplace.contactrequest'),
        ),
        migrations.CreateModel(
            name='ProfessionalObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('operador', 'Operador'), ('motorista_caminhao', 'Motorista de caminhao'), ('encarregado', 'Encarregado'), ('engenheiro', 'Engenheiro')], max_length=30)),
                ('summary', models.CharField(blank=True, max_length=180)),
                ('salary_expectation', models.CharField(blank=True, max_length=80)),
                ('availability', models.CharField(blank=True, max_length=120)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('review', 'Em analise'), ('published', 'Publicado'), ('paused', 'Pausado'), ('rejected', 'Recusado')], default='review', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_objectives', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_professional_objectives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('role',),
            },
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to='marketplace.professionalobjective'),
        ),
        migrations.AddIndex(
            model_name='professionalobjective',
            index=models.Index(fields=['role', 'status'], name='marketplace_role_9a40ae_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalobjective',
            index=models.Index(fields=['professional', 'status'], name='marketplace_profess_71537a_idx'),
        ),
        migrations.AddConstraint(
            model_name='professionalobjective',
            constraint=models.UniqueConstraint(fields=('professional', 'role'), name='unique_professional_objective_role'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['company', 'status', '-created_at'], name='marketplace_company_6da5cd_idx'),
        ),
        migrations.AddIndex(
            model_name='contactrequest',
            index=models.Index(fields=['professional', 'status', '-created_at'], name='marketplace_profess_d962c0_idx'),
        ),
    ]
