# Generated by Django 5.2.15 on 2026-06-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_notification_kind_contactrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalobjective',
            name='role',
            field=models.CharField(choices=[('operador', 'Operador'), ('motorista_caminhao', 'Motorista de caminhao'), ('encarregado', 'Encarregado'), ('engenheiro', 'Engenheiro'), ('outros', 'Outros')], max_length=30),
        ),
    ]
