# Generated by Django 5.2.15 on 2026-06-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_alter_professionalobjective_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'ordering': ('-created_at',), 'verbose_name': '02. Solicitacao de contato', 'verbose_name_plural': '02. Solicitacoes de contato'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',), 'verbose_name': '03. Aviso', 'verbose_name_plural': '03. Avisos'},
        ),
        migrations.AlterModelOptions(
            name='professionalobjective',
            options={'ordering': ('role',), 'verbose_name': '01. Area profissional', 'verbose_name_plural': '01. Areas profissionais'},
        ),
    ]
